/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { ButtonVariantType } from './components/atoms/button/button-props';
import { IconNames } from './components/atoms/icon/icon-props';
export namespace Components {
    interface UiButton {
        /**
         * Class button
         * @default ""
         */
        class: string;
        /**
         * Disable button
         * @default false
         */
        disabled: boolean;
        /**
         * Button variant
         * @default primary
         */
        variant: ButtonVariantType;
    }
    interface UiIcon {
        /**
         * Class button
         * @default ""
         */
        class: string;
        iconName: IconNames;
    }
}
declare global {
    interface HTMLUiButtonElement
        extends Components.UiButton,
            HTMLStencilElement {}
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {}
    var HTMLUiIconElement: {
        prototype: HTMLUiIconElement;
        new (): HTMLUiIconElement;
    };
    interface HTMLElementTagNameMap {
        'ui-button': HTMLUiButtonElement;
        'ui-icon': HTMLUiIconElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        /**
         * Class button
         * @default ""
         */
        class?: string;
        /**
         * Disable button
         * @default false
         */
        disabled?: boolean;
        /**
         * Button variant
         * @default primary
         */
        variant?: ButtonVariantType;
    }
    interface UiIcon {
        /**
         * Class button
         * @default ""
         */
        class?: string;
        iconName?: IconNames;
    }
    interface IntrinsicElements {
        'ui-button': UiButton;
        'ui-icon': UiIcon;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'ui-button': LocalJSX.UiButton &
                JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            'ui-icon': LocalJSX.UiIcon &
                JSXBase.HTMLAttributes<HTMLUiIconElement>;
        }
    }
}
